<script setup>
import AboutTaxesItem from '@/components/Taxes/AboutTaxes/AboutTaxesItem.vue';
import {aboutTaxes1, aboutTaxes2, aboutTaxes3, aboutTaxes4} from "@/assets/images";
</script>

<template>
  <section class="about-taxes">
    <AboutTaxesItem
      :img="aboutTaxes1"
      title="Less tax, more cash"
      text="Tax credits can be paid to the IRS directly instead of cash.
            By buying these credits at a discount to their face value through Evergrow,
            you can achieve significant savings on your taxes, earn high IRRs on cash
            in treasury, and boost after-tax cashflow."
    />
    <AboutTaxesItem
      :img="aboutTaxes2"
      title="Lead on climate"
      text="Green tax credits are generated by clean energy and other climate-friendly
            assets in the United States, including solar, wind, and carbon capture.
            By buying these credits through Evergrow, you provide critical funding
            for these projects and position your company as a leader on climate change."
    />
    <AboutTaxesItem
      :img="aboutTaxes3"
      title="Safe, secure, and protected"
      text="Large banks and financial institutions have used green tax credits
            for over a decade. With Evergrow, now you can too. And as an added
            layer of protection, all green tax credits on Evergrow are protected
            by an insurance policy from a highly rated syndicate of insurers,
            so you can invest with confidence."
    />
    <AboutTaxesItem
      :img="aboutTaxes4"
      title="Simple and easy to use"
      text="Evergrow is the first all-in-one platform for green tax credits.
            We handle project sourcing, diligence, and management so you
            don’t have to, and we can work with any budget and timeline."
    />
  </section>
</template>

<style scoped>
  .about-taxes {
    @apply flex flex-col my-14 px-[200px]
  }
</style>
